---
# tasks file for ansible-bind
- ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- ansible.builtin.include_tasks: config_bind.yml
  when: bind_config|bool

- ansible.builtin.include_tasks: manage_zones.yml
  when: bind_manage_zones
